### ISSUE TITLE
04-array-object/02-sort 클래스명 오타

### ISSUE THREAD

**Issue by goyach0i** [erumcoding/js-project-101#1]
## 예제 오타 부분
  `<button class="asceding">가격 오름차순 정렬</button>`
  `<button class="ascending">가격 오름차순 정렬</button>`

## 오타 수정 (button className)
 asceding => ascending

**Comment by dohaelee** [comment]
수정 완료 되었습니다. 제보 감사드립니다.

---

Related Commits: [e3d1e48](04-array-object/02-sort/index.html), [7983d5c](https://github.com/erumcoding/js-project-101/commit/7983d5c6e2d304118f8a35ed355be3d0baa806c3)
